### ISSUE TITLE
JSON RPC client and SpringBoot integration

### ISSUE THREAD

**Issue by dmitry-at-hyla** [dmitry-at-hyla/voorhees#57]
Let define the client through auto-configuration. Let's say having this:
```yaml
voorhees:
  client:
    services:
      default:
        endpoint: http://api.server.com/
      user-service:
        endpoint: http://user.server.com/api
        targets: packages.containing.service.classes, service.classes.ThemSelves
```
we are able to just autowire auto-generated services like that:
```java
@Autowired
private MyRemoteService myService;
```
and if `MyRemoteService` is defined in some `targets` it will be bound to this particular service, otherwise it will be bound to `default` service if it exists.

On the server side we could define default service-name so if a service has it, this name will be used as a service name instead of `default` on the client side. The question: how to define it? On the service level? application? during generating client library?
